### ISSUE TITLE
Old wolf doesn't update.

### ISSUE THREAD

**Issue by Quocnam201010** [HeroGamers/MyDog#100]
### Type of bug

Error in console, Other unexpected behaviour

### Bug description

When I first time add the plugin to my server, every time i right clicked on the old wolf, it updates to the new wolf. But when I restart the server, the old wolfs no longer update.

### Steps to reproduce

1. Download the plugin and launch the server.
2. Update some old wolves
3. Restart the server.

### Expected behaviour

Old wolves update to new wolves

### Actual behaviour

Old wolves don't update to new wolves

**Comment by Quocnam201010** [comment]
Forgot to mention:
every second, the console show this:
[02:38:23 WARN]: [MyDog] Task #9 for MyDog v0.2.1 generated an exception
java.lang.NullPointerException: Cannot invoke "String.length()" because "text" is null
        at java.text.SimpleDateFormat.parse(SimpleDateFormat.java:1474) ~[?:?]
        at java.text.DateFormat.parse(DateFormat.java:397) ~[?:?]
        at dk.fido2603.mydog.objects.Dog.getBirthday(Dog.java:166) ~[mydog-0.2.1.jar:?]
        at dk.fido2603.mydog.objects.Dog.<init>(Dog.java:101) ~[mydog-0.2.1.jar:?]
        at dk.fido2603.mydog.managers.DogManager.getDogs(DogManager.java:194) ~[mydog-0.2.1.jar:?]
        at dk.fido2603.mydog.managers.DogManager.getAliveDogs(DogManager.java:203) ~[mydog-0.2.1.jar:?]
        at dk.fido2603.mydog.tasks.AttackModeTask.run(AttackModeTask.java:20) ~[mydog-0.2.1.jar:?]
        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.4.jar:git-Paper-538]
        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.19.4.jar:git-Paper-538]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1483) ~[paper-1.19.4.jar:git-Paper-538]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.19.4.jar:git-Paper-538]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.4.jar:git-Paper-538]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1174) ~[paper-1.19.4.jar:git-Paper-538]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper-1.19.4.jar:git-Paper-538]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by Quocnam201010** [comment]
Forgot to mention again. When i delete both config folder and jar file and redownload the plugin, the old wolves updates again.

**Comment by HeroGamers** [comment]
Thanks for the bug report, I'll take a look into it!

**Comment by HeroGamers** [comment]
I fixed the console error, but I need more info for the rest, with the old wolves not updating?
It works fine on my end when testing, so if possible, I would like some more information on this.

The issue might auto-close because I fixed the other thing, but feel free to reopen the issue!
