### ISSUE TITLE
Revive command/permissions not available? 

### ISSUE THREAD

**Issue by AKASGaming** [HeroGamers/MyDog#61]
I see that revive is now a thing, but is it fully implemented yet? I can't seem to be able to run the /md revive command. It shows no errors in the console or in the player's chat.

**Comment by AKASGaming** [comment]
Update: the command doesn't work by itself, it requires a dog ID. After that, it still errors

**Comment by HeroGamers** [comment]
You say that it errors after providing a dog ID - what sort of error?

The permission is implemented into the plugin, and is `mydog.revive` - though operators can also perform the command by default. However, revivals require Revival to be enabled in the config - and also for the dead dog to appear in the dead dogs list.

Is the dog in the dogs.yml file?

The feature is new, so there might be some bugs - however it worked quite well from the testing I did on it.

I'd love to hear if this is an issue that others experience as well, and what the configuration is then.

**Comment by AKASGaming** [comment]
Error:
```
[19:00:14] [Server thread/INFO]: biz_kid1 issued server command: /mydog revive 2
[19:00:14] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'mydog' in plugin MyDog v0.1.4
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[spigot-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.dispatchCommand(CraftServer.java:829) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3443-Spigot-699290c-2c1e499]
        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1941) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3443-Spigot-699290c-2c1e499]
        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1780) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3443-Spigot-699290c-2c1e499]
        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1761) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3443-Spigot-699290c-2c1e499]
        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3443-Spigot-699290c-2c1e499]
        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3443-Spigot-699290c-2c1e499]
        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:30) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3443-Spigot-699290c-2c1e499]
        at net.minecraft.server.TickTask.run(SourceFile:18) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3443-Spigot-699290c-2c1e499]
        at net.minecraft.util.thread.IAsyncTaskHandler.c(SourceFile:151) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3443-Spigot-699290c-2c1e499]
        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.c(SourceFile:23) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3443-Spigot-699290c-2c1e499]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1158) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3443-Spigot-699290c-2c1e499]
        at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:1) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3443-Spigot-699290c-2c1e499]
        at net.minecraft.util.thread.IAsyncTaskHandler.y(SourceFile:125) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3443-Spigot-699290c-2c1e499]
        at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1137) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3443-Spigot-699290c-2c1e499]
        at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1130) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3443-Spigot-699290c-2c1e499]
        at net.minecraft.util.thread.IAsyncTaskHandler.c(SourceFile:134) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3443-Spigot-699290c-2c1e499]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1114) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3443-Spigot-699290c-2c1e499]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1038) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3443-Spigot-699290c-2c1e499]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3443-Spigot-699290c-2c1e499]
        at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.lang.NoClassDefFoundError: net/milkbowl/vault/economy/Economy
        at dk.fido2603.mydog.managers.CommandManager.commandReviveDog(CommandManager.java:582) ~[?:?]
        at dk.fido2603.mydog.managers.CommandManager.onCommand(CommandManager.java:179) ~[?:?]
        at dk.fido2603.mydog.MyDog.onCommand(MyDog.java:457) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[spigot-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        ... 21 more
Caused by: java.lang.ClassNotFoundException: net.milkbowl.vault.economy.Economy
        at dk.fido2603.mydog.managers.CommandManager.commandReviveDog(CommandManager.java:582) ~[?:?]
        at dk.fido2603.mydog.managers.CommandManager.onCommand(CommandManager.java:179) ~[?:?]
        at dk.fido2603.mydog.MyDog.onCommand(MyDog.java:457) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[spigot-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        ... 21 more
```

**Comment by HeroGamers** [comment]
Ah, I see. It's caused by the plugin trying to get your Economy provider to subtract some currency for the revival.
Do you have Vault installed on the server - and what Economy provider do you use? (ie. Essentials)

But yeah, this should definitely be caught instead of just dying - so I will put a check in to disable the command (or make revivals free) if no Economy plugin is found.
Thanks!

**Comment by AKASGaming** [comment]
I do not have an economy system on the server, I just assumed it was free 😅

**Comment by HeroGamers** [comment]
I'll look into either disabling the check if an economy system is not found, or if the price is set to 0.
