### ISSUE TITLE
Spam error on console with task exception

### ISSUE THREAD

**Issue by 4L3X4NDD3R** [HeroGamers/MyDog#81]
Task # for Mydog generated an exception java.lang.nullpointerExepctionnull
[https://imgur.com/lqChI0D](url)

**Comment by HeroGamers** [comment]
Can you try giving some more information?
What version of Spigot/Bukkit are you using?
Can you try enabling debug for the plugin?

**Comment by naitkodeks** [comment]
[29.05 18:40:15] [Server] [WARN] [MyDog] Task #16 for MyDog v0.1.4 generated an exception
[29.05 18:40:15] [Server] java.lang.NullPointerExceptionnull
[29.05 18:40:18] [Server] [INFO] Nightcodex issued server command: /lp reloadconfig
[29.05 18:40:19] [Server] [WARN] [MyDog] Task #16 for MyDog v0.1.4 generated an exception
[29.05 18:40:19] [Server] java.lang.NullPointerExceptionnull
[29.05 18:40:21] [Server] [WARN] [MyDog] Task #16 for MyDog v0.1.4 generated an exception
[29.05 18:40:21] [Server] java.lang.NullPointerExceptionnull
[29.05 18:40:23] [Server] [WARN] [MyDog] Task #16 for MyDog v0.1.4 generated an exception
[29.05 18:40:23] [Server] java.lang.NullPointerExceptionnull
[29.05 18:40:24] [Server] [WARN] [MyDog] Task #15 for MyDog v0.1.4 generated an exception
[29.05 18:40:24] [Server] java.lang.NullPointerExceptionnull
[29.05 18:40:24] [Server] [WARN] [MyDog] Task #16 for MyDog v0.1.4 generated an exception
[29.05 18:40:24] [Server] java.lang.NullPointerExceptionnull
[29.05 18:40:26] [Server] [WARN] [MyDog] Task #16 for MyDog v0.1.4 generated an exception
[29.05 18:40:26] [Server] java.lang.NullPointerExceptionnull
[29.05 18:40:28] [Server] [WARN] [MyDog] Task #16 for MyDog v0.1.4 generated an exception
[29.05 18:40:28] [Server] java.lang.NullPointerExceptionnull
[29.05 18:40:29] [Server] [WARN] [MyDog] Task #16 for MyDog v0.1.4 generated an exception
[29.05 18:40:29] [Server] java.lang.NullPointerExceptionnull
[29.05 18:40:32] [Server] [WARN] [MyDog] Task #16 for MyDog v0.1.4 generated an exception
[29.05 18:40:32] [Server] java.lang.NullPointerExceptionnull
[29.05 18:40:34] [Server] [WARN] [MyDog] Task #15 for MyDog v0.1.4 generated an exception
[29.05 18:40:34] [Server] java.lang.NullPointerExceptionnull
[29.05 18:40:34] [Server] [WARN] [MyDog] Task #16 for MyDog v0.1.4 generated an exception
[29.05 18:40:34] [Server] java.lang.NullPointerExceptionnull
[29.05 18:40:36] [Server] [WARN] [MyDog] Task #16 for MyDog v0.1.4 generated an exception
[29.05 18:40:36] [Server] java.lang.NullPointerExceptionnull
[29.05 18:40:37] [Server] [INFO] [UltimateAutoRestart] » Restarting in 30s!
[29.05 18:40:37] [Server] [WARN] [MyDog] Task #16 for MyDog v0.1.4 generated an exception
[29.05 18:40:37] [Server] java.lang.NullPointerExceptionnull
[29.05 18:40:39] [Server] [WARN] [MyDog] Task #16 for MyDog v0.1.4 generated an exception
[29.05 18:40:39] [Server] java.lang.NullPointerExceptionnull
[29.05 18:40:41] [Server] [WARN] [MyDog] Task #16 for MyDog v0.1.4 generated an exception
[29.05 18:40:41] [Server] java.lang.NullPointerExceptionnull
[29.05 18:40:43] [Server] [WARN] [MyDog] Task #15 for MyDog v0.1.4 generated an exception
[29.05 18:40:43] [Server] java.lang.NullPointerExceptionnull
[29.05 18:40:43] [Server] [WARN] [MyDog] Task #16 for MyDog v0.1.4 generated an exception
[29.05 18:40:43] [Server] java.lang.NullPointerExceptionnull
[29.05 18:40:44] [Server] [INFO] [ClearLag] 648 Mobs have been removed!
[29.05 18:40:44] [Server] [INFO] [ClearLag] You just removed 37 entities!
[29.05 18:40:44] [Server] [INFO] [ClearLag] Server activity has been halted!
[29.05 18:40:45] [Server] [INFO] [LP] LOG > (Nightcodex) [G] (default)
[29.05 18:40:45] [Server] [INFO] [LP] LOG > webeditor add mydog.teleport true
[29.05 18:40:45] [Server] [WARN] [MyDog] Task #16 for MyDog v0.1.4 generated an exception
[29.05 18:40:45] [Server] java.lang.NullPointerExceptionnull
[29.05 18:40:47] [Server] [WARN] [MyDog] Task #16 for MyDog v0.1.4 generated an exception
[29.05 18:40:47] [Server] java.lang.NullPointerExceptionnull
[29.05 18:40:49] [Server] [WARN] [MyDog] Task #16 for MyDog v0.1.4 generated an exception
[29.05 18:40:49] [Server] java.lang.NullPointerExceptionnull
[29.05 18:40:51] [Server] [WARN] [MyDog] Task #16 for MyDog v0.1.4 generated an exception
[29.05 18:40:51] [Server] java.lang.NullPointerExceptionnull
[29.05 18:40:53] [Server] [INFO] Kuga_ issued server command: /mydog dogs
[29.05 18:40:53] [Server] [ERROR] null
[29.05 18:40:53] [Server] org.bukkit.command.CommandExceptionUnhandled exception executing command 'mydog' in plugin MyDog v0.1.4
[29.05 18:40:53] [Server] 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
[29.05 18:40:53] [Server] 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
[29.05 18:40:53] [Server] 	at org.bukkit.craftbukkit.v1_19_R3.CraftServer.dispatchCommand(CraftServer.java:907) ~[paper-1.19.4.jar:git-Paper-540]
[29.05 18:40:53] [Server] 	at org.bukkit.craftbukkit.v1_19_R3.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[paper-1.19.4.jar:git-Paper-540]
[29.05 18:40:53] [Server] 	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264) ~[paper-1.19.4.jar:?]
[29.05 18:40:53] [Server] 	at net.minecraft.commands.Commands.performCommand(Commands.java:322) ~[?:?]
[29.05 18:40:53] [Server] 	at net.minecraft.commands.Commands.performCommand(Commands.java:306) ~[?:?]
[29.05 18:40:53] [Server] 	at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2297) ~[?:?]
[29.05 18:40:53] [Server] 	at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$20(ServerGamePacketListenerImpl.java:2257) ~[?:?]
[29.05 18:40:53] [Server] 	at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
[29.05 18:40:53] [Server] 	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
[29.05 18:40:53] [Server] 	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.4.jar:git-Paper-540]
[29.05 18:40:53] [Server] 	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
[29.05 18:40:53] [Server] 	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
[29.05 18:40:53] [Server] 	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1342) ~[paper-1.19.4.jar:git-Paper-540]
[29.05 18:40:53] [Server] 	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.19.4.jar:git-Paper-540]
[29.05 18:40:53] [Server] 	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
[29.05 18:40:53] [Server] 	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1319) ~[paper-1.19.4.jar:git-Paper-540]
[29.05 18:40:53] [Server] 	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1312) ~[paper-1.19.4.jar:git-Paper-540]
[29.05 18:40:53] [Server] 	at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[?:?]
[29.05 18:40:53] [Server] 	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1428) ~[paper-1.19.4.jar:git-Paper-540]
[29.05 18:40:53] [Server] 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1174) ~[paper-1.19.4.jar:git-Paper-540]
[29.05 18:40:53] [Server] 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper-1.19.4.jar:git-Paper-540]
[29.05 18:40:53] [Server] 	at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by naitkodeks** [comment]
[29.05 18:47:07] [Server] [WARN] [MyDog] Task #15 for MyDog v0.1.4 generated an exception
[29.05 18:47:07] [Server] java.lang.NullPointerExceptionCannot invoke "org.bukkit.World.getName()" because the return value of "org.bukkit.Location.getWorld()" is null
[29.05 18:47:07] [Server] 	at dk.fido2603.mydog.objects.Dog.syncDog(Dog.java:601) ~[MyDog-0.1.4.jar:?]
[29.05 18:47:07] [Server] 	at dk.fido2603.mydog.objects.Dog.<init>(Dog.java:113) ~[MyDog-0.1.4.jar:?]
[29.05 18:47:07] [Server] 	at dk.fido2603.mydog.managers.DogManager.getDogs(DogManager.java:161) ~[MyDog-0.1.4.jar:?]
[29.05 18:47:07] [Server] 	at dk.fido2603.mydog.managers.DogManager.getAliveDogs(DogManager.java:170) ~[MyDog-0.1.4.jar:?]
[29.05 18:47:07] [Server] 	at dk.fido2603.mydog.MyDog$1.run(MyDog.java:254) ~[MyDog-0.1.4.jar:?]
[29.05 18:47:07] [Server] 	at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.4.jar:git-Paper-540]
[29.05 18:47:07] [Server] 	at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.19.4.jar:git-Paper-540]
[29.05 18:47:07] [Server] 	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1483) ~[paper-1.19.4.jar:git-Paper-540]
[29.05 18:47:07] [Server] 	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.19.4.jar:git-Paper-540]
[29.05 18:47:07] [Server] 	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.4.jar:git-Paper-540]
[29.05 18:47:07] [Server] 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1174) ~[paper-1.19.4.jar:git-Paper-540]
[29.05 18:47:07] [Server] 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper-1.19.4.jar:git-Paper-540]
[29.05 18:47:07] [Server] 	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[29.05 18:47:07] [Server] [WARN] [MyDog] Task #16 for MyDog v0.1.4 generated an exception
[29.05 18:47:07] [Server] java.lang.NullPointerExceptionCannot invoke "org.bukkit.World.getName()" because the return value of "org.bukkit.Location.getWorld()" is null
[29.05 18:47:07] [Server] 	at dk.fido2603.mydog.objects.Dog.syncDog(Dog.java:601) ~[MyDog-0.1.4.jar:?]
[29.05 18:47:07] [Server] 	at dk.fido2603.mydog.objects.Dog.<init>(Dog.java:113) ~[MyDog-0.1.4.jar:?]
[29.05 18:47:07] [Server] 	at dk.fido2603.mydog.managers.DogManager.getDogs(DogManager.java:161) ~[MyDog-0.1.4.jar:?]
[29.05 18:47:07] [Server] 	at dk.fido2603.mydog.managers.DogManager.getAliveDogs(DogManager.java:170) ~[MyDog-0.1.4.jar:?]
[29.05 18:47:07] [Server] 	at dk.fido2603.mydog.MyDog$2.run(MyDog.java:291) ~[MyDog-0.1.4.jar:?]
[29.05 18:47:07] [Server] 	at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.4.jar:git-Paper-540]
[29.05 18:47:07] [Server] 	at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.19.4.jar:git-Paper-540]
[29.05 18:47:07] [Server] 	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1483) ~[paper-1.19.4.jar:git-Paper-540]
[29.05 18:47:07] [Server] 	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.19.4.jar:git-Paper-540]
[29.05 18:47:07] [Server] 	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.4.jar:git-Paper-540]
[29.05 18:47:07] [Server] 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1174) ~[paper-1.19.4.jar:git-Paper-540]
[29.05 18:47:07] [Server] 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper-1.19.4.jar:git-Paper-540]
[29.05 18:47:07] [Server] 	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[29.05 18:47:09] [Server] [WARN] [MyDog] Task #16 for MyDog v0.1.4 generated an exception
[29.05 18:47:09] [Server] java.lang.NullPointerExceptionCannot invoke "org.bukkit.World.getName()" because the return value of "org.bukkit.Location.getWorld()" is null
[29.05 18:47:09] [Server] 	at dk.fido2603.mydog.objects.Dog.syncDog(Dog.java:601) ~[MyDog-0.1.4.jar:?]
[29.05 18:47:09] [Server] 	at dk.fido2603.mydog.objects.Dog.<init>(Dog.java:113) ~[MyDog-0.1.4.jar:?]
[29.05 18:47:09] [Server] 	at dk.fido2603.mydog.managers.DogManager.getDogs(DogManager.java:161) ~[MyDog-0.1.4.jar:?]
[29.05 18:47:09] [Server] 	at dk.fido2603.mydog.managers.DogManager.getAliveDogs(DogManager.java:170) ~[MyDog-0.1.4.jar:?]
[29.05 18:47:09] [Server] 	at dk.fido2603.mydog.MyDog$2.run(MyDog.java:291) ~[MyDog-0.1.4.jar:?]
[29.05 18:47:09] [Server] 	at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.4.jar:git-Paper-540]
[29.05 18:47:09] [Server] 	at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.19.4.jar:git-Paper-540]
[29.05 18:47:09] [Server] 	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1483) ~[paper-1.19.4.jar:git-Paper-540]
[29.05 18:47:09] [Server] 	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.19.4.jar:git-Paper-540]
[29.05 18:47:09] [Server] 	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.4.jar:git-Paper-540]
[29.05 18:47:09] [Server] 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1174) ~[paper-1.19.4.jar:git-Paper-540]
[29.05 18:47:09] [Server] 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper-1.19.4.jar:git-Paper-540]
[29.05 18:47:09] [Server] 	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[29.05 18:47:10] [Server] [INFO] Named entity EntityPigZombie['〖12〗 Cookie the Cook'/15325, uuid='952330eb-4041-4626-9bb0-282cc37d0964', l='ServerLevel[world]', x=2951.80, y=67.00, z=-3043.44, cpos=[184, -191], tl=760, v=true] died: 〖12〗 Cookie the Cook was slain by Thofro using [Netherite Blade]
[29.05 18:47:12] [Server] [WARN] [MyDog] Task #16 for MyDog v0.1.4 generated an exception
[29.05 18:47:12] [Server] java.lang.NullPointerExceptionCannot invoke "org.bukkit.World.getName()" because the return value of "org.bukkit.Location.getWorld()" is null
[29.05 18:47:12] [Server] 	at dk.fido2603.mydog.objects.Dog.syncDog(Dog.java:601) ~[MyDog-0.1.4.jar:?]
[29.05 18:47:12] [Server] 	at dk.fido2603.mydog.objects.Dog.<init>(Dog.java:113) ~[MyDog-0.1.4.jar:?]
[29.05 18:47:12] [Server] 	at dk.fido2603.mydog.managers.DogManager.getDogs(DogManager.java:161) ~[MyDog-0.1.4.jar:?]
[29.05 18:47:12] [Server] 	at dk.fido2603.mydog.managers.DogManager.getAliveDogs(DogManager.java:170) ~[MyDog-0.1.4.jar:?]
[29.05 18:47:12] [Server] 	at dk.fido2603.mydog.MyDog$2.run(MyDog.java:291) ~[MyDog-0.1.4.jar:?]
[29.05 18:47:12] [Server] 	at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.4.jar:git-Paper-540]
[29.05 18:47:12] [Server] 	at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.19.4.jar:git-Paper-540]
[29.05 18:47:12] [Server] 	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1483) ~[paper-1.19.4.jar:git-Paper-540]
[29.05 18:47:12] [Server] 	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.19.4.jar:git-Paper-540]
[29.05 18:47:12] [Server] 	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.4.jar:git-Paper-540]
[29.05 18:47:12] [Server] 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1174) ~[paper-1.19.4.jar:git-Paper-540]
[29.05 18:47:12] [Server] 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper-1.19.4.jar:git-Paper-540]
[29.05 18:47:12] [Server] 	at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by HeroGamers** [comment]
There's enough information about the second error @naitkodeks has, but I don't have enough information for the first error (task 15).

But you should try updating to v0.2.0, since you're still running v0.1.4.
I will release some bugfixes in an hour or so to address some other issues, in v0.2.1.

**Comment by HeroGamers** [comment]
For other issues, please open a new bug report, as these issues doesn't seem to be related.
